# Imports

In [52]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LinearRegression, LassoCV, Ridge, LogisticRegression, BayesianRidge, TweedieRegressor 
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier

from sklearn import tree
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

# DataFrame et Data

In [28]:
df = pd.read_csv('logicimmo - Copie.csv')
X = df.drop('Prix (Euros)', axis = 1)
y = df['Prix (Euros)']

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Modèles  :

### Regression linéaire 

In [30]:
model_lin_reg = LinearRegression()
model_lin_reg.fit(X_train,y_train)
model_lin_reg.score(X_test,y_test)

0.8480505498768764

In [31]:
cross_val_score(model_lin_reg, X, y, cv=5)

array([  0.79090888, -83.48100222,   0.78531564,   0.83156989,
        -2.8694372 ])

In [32]:
linear_selector = SelectFromModel(LinearRegression(),threshold='mean')
linear_selector.fit_transform(X,y)
linear_selector.get_support()

array([ True,  True,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False, False])

### Lasso CV

In [33]:
model_lasso_cv = LassoCV(cv=5)
model_lasso_cv.fit(X_train, y_train)
model_lasso_cv.score(X_test, y_test)

0.845498660153428

In [34]:
cross_val_score(model_lasso_cv, X, y, cv=5)

array([  0.7908616 , -83.75179355,   0.77818214,   0.82865153,
        -3.22061011])

In [35]:
lasso_selector = SelectFromModel(LassoCV(cv=5),threshold='mean')
lasso_selector.fit_transform(X,y)
lasso_selector.get_support()

array([ True,  True,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False, False])

### Ridge

In [36]:
model_ridge = Ridge()
model_ridge.fit(X_train, y_train)
model_ridge.score(X_test, y_test)

0.8480504683065228

In [37]:
cross_val_score(model_ridge, X, y, cv=5)

array([  0.79091685, -83.47632586,   0.78531354,   0.83164108,
        -2.86854223])

In [38]:
Ridge_selector = SelectFromModel(Ridge(),threshold='mean')
Ridge_selector.fit_transform(X,y)
Ridge_selector.get_support()

array([ True,  True,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False, False])

### SVR

In [39]:
model_SVR = SVR(kernel='rbf')
model_SVR.fit(X_train,y_train)
model_SVR.score(X_test,y_test)

-0.07699059018769616

### DecisionTreeClassifier

In [40]:
model_decision_tree = tree.DecisionTreeClassifier()
model_decision_tree.fit(X_train,y_train)
model_decision_tree.score(X_test,y_test)

0.2315891472868217

In [41]:
cross_val_score(model_decision_tree, X, y, cv=5)

C:\Users\kju78\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,


array([0.26647287, 0.2900097 , 0.27449079, 0.25121242, 0.19786615])

In [42]:
selector_tree = SelectFromModel(tree.DecisionTreeClassifier(),threshold='mean')
selector_tree.fit_transform(X,y)
selector_tree.get_support()

array([ True, False, False,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False])

### RandomForestClassifier

In [43]:
model_random_forest = RandomForestClassifier(n_estimators=10)
model_random_forest.fit(X_train,y_train)
model_random_forest.score(X_test,y_test)

0.19767441860465115

In [44]:
cross_val_score(model_random_forest, X, y, cv=5)

C:\Users\kju78\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,


array([0.22286822, 0.2356935 , 0.2599418 , 0.2356935 , 0.15033948])

In [45]:
selector_random_forest = SelectFromModel(RandomForestClassifier(n_estimators=10),threshold='mean')
selector_random_forest.fit_transform(X,y)
selector_random_forest.get_support()

array([ True, False, False,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False])

### SGDClassifier

In [23]:
model_SGD = SGDClassifier(max_iter=1000, tol=0.01)
model_SGD.fit(X_train,y_train)
model_SGD.score(X_test,y_test)

C:\Users\kju78\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:700: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning,


0.0009689922480620155

### LogisticRegression

In [46]:
model_logistic_reg = LogisticRegression()
model_logistic_reg.fit(X_train,y_train)
model_logistic_reg.score(X_test,y_test)

C:\Users\kju78\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.02131782945736434

### BayesianRidge

In [48]:
model_bayesian = BayesianRidge()
model_bayesian.fit(X_train, y_train)
model_bayesian.score(X_test, y_test)

0.8480596366403497

In [49]:
cross_val_score(model_bayesian, X, y, cv=5)

array([  0.79124067, -83.15788254,   0.78519372,   0.83313848,
        -2.8408571 ])

In [50]:
selector_bayesian = SelectFromModel(BayesianRidge(),threshold='mean')
selector_bayesian.fit_transform(X,y)
selector_bayesian.get_support()

array([ True,  True,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False, False])

### TweedieRegressor

In [60]:
model_tweedie = TweedieRegressor(max_iter=1000)
model_tweedie.fit(X_train, y_train)
model_tweedie.score(X_test, y_test)

0.8447911855036547

In [61]:
cross_val_score(model_tweedie, X, y, cv=5)

array([  0.79298073, -83.03996912,   0.77652359,   0.8257756 ,
        -3.21383296])

In [63]:
selector_tweedie = SelectFromModel(TweedieRegressor(max_iter=1000),threshold='mean')
selector_tweedie.fit_transform(X,y)
selector_tweedie.get_support()

array([ True,  True,  True, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False])